### ISSUE TITLE
Bootstrap Project

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-spills#126]
Create a new react web app from latest atlas template as well as a Salesforce dev environment.

### Tasks
- [x] Copy atlas latest template tearing out anything that we don't need
- [x] Update/copy Salesforce development template (ask Barry for a recommendation on the latest and greatest) 

~- [ ] [Upgrade salesforce project to TypeScript](https://developer.salesforce.com/docs/platform/lwc/guide/ts.html)~
It's half-baked so I decided not to do it.

- [x] Wire up linting for salesforce folder
- [x] Update cloud infrastructure via terraform (e.g. secrets)
- [x] Diagram networking and data flow for Archer
- [x] [Move from sfdx (v7) to sf (v2)](https://developer.salesforce.com/docs/atlas.en-us.sfdx_setup.meta/sfdx_setup/sfdx_setup_move_to_sf_v2.htm)

**Comment by stdavis** [comment]
Archer diagrams have been started and can be found in the "UGRC Security Engineers" Lucid team. They should be finalized before a production deploy. There are a few architecture decisions that need to be ironed out before they can be completed.
