### ISSUE TITLE
Determine Incident Proximity to Surface Water

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-spills#127]
From client:
>When a spill location is created or updated for an incident, the map widget should automatically find the nearest waterbody ([using NHD data from SGID](https://opendata.gis.utah.gov/search?q=nhd) within a reasonable distance) and update Salesforce fields with the waterbody name and distance.

This could possibly be accomplished by querying the relevant NHD data within the search radius and then looping through each returned geometry to find the one that is closest.

Clarifications from Sarah:
Reasonable distance is 1 mile.

Here are the layers that they want searched:
[https://opendata.gis.utah.gov/datasets/utah::utah-major-streams-statewide/about](https://www.google.com/url?q=https://opendata.gis.utah.gov/datasets/utah::utah-major-streams-statewide/about&sa=D&source=docs&ust=1740422760806008&usg=AOvVaw0Cr5nQ5zAIwOyz_lDKWDKR)
[https://opendata.gis.utah.gov/datasets/utah::utah-major-rivers-polygons/about](https://www.google.com/url?q=https://opendata.gis.utah.gov/datasets/utah::utah-major-rivers-polygons/about&sa=D&source=docs&ust=1740422760806020&usg=AOvVaw2QqvDxdHdezNUn8TzJbq3f)

Internal only for now with a URL parameter to toggle functionality similar to flowpaths.

### Tasks

- [x] Determine which NHD layers, specifically, they would like searched (submitted this question to Sarah on 10/15)
- [x] Determine what a "reasonable distance" is
- [x] Determine what salesforce field should hold this data
- [x] Create a trigger for any time a spill location is created or updated
- [x] Query NDH layer(s)
- [x] Write value to Salesforce

**Comment by steveoh** [comment]
I've used this before with postgis to find the closest record.

https://github.com/steveoh/Presentations/blob/6d5236441a1d6ff3e2ef034ea8bb404fb55327d7/2020/DowntownCodingSLC/2-command-line-with-parameters/main.py#L56-L61

**Comment by steveoh** [comment]
I think that operator is only available in pg directly.

**Comment by stdavis** [comment]
Maybe this is already supported via the web api.

**Comment by stdavis** [comment]
Proposed field names. Waiting on Rahul to give us the final versions:

NearestWaterbodyName (text field, 250 characters)
NearestWaterbodyDistance (numeric, integer field in feet)
NearestWaterbodyID (text field, 50 characters) - This is for the component's internal implementation and would not necessarily need to be displayed to users.

**Comment by chriswnek** [comment]
The below new fields have been added to the Salesforce EID sandbox:
- `NearestWaterbodyDistance__c` :Number(18 total digits, 0 decimal points)
- `NearestWaterbodyID__c` :Text(255), Unique
- `NearestWaterbodyName__c` :Text(255)

**Comment by acneville** [comment]
Currently have been able to fetch the fields from NHD as requested. The distance, ID, and name are all computed. Working on next full integration steps currently.

**Comment by acneville** [comment]
Integration working in staging. Will await further feedback for UI/UX and other requested features, should they arise, then will target production release. 

<img width="1129" height="731" alt="Image" src="https://github.com/user-attachments/assets/f3f883c8-ee53-4eb1-a1e8-e4c944b18deb" />
