### ISSUE TITLE
Add Reference Layers

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-spills#128]
From client request:
>Incorporate a drinking water source layer onto the map to assist in identifying when to notify the Division of Drinking Water (DDW).
This will be a toggleable reference layer that will default to off.
Use the “Public Water System Facilities” layer from the interactive map.

>Display property owner and owner types (private, BLM, SITLA, tribal areas) for nearby areas.
This data should come from the [SITLA Land Ownership](https://opendata.gis.utah.gov/datasets/SITLA::land-ownership/about) feature service’s “OWNER AGENCY” field.

I've submitted clarification on what they want labeled or if they want a popup for the DDW layer.

### Tasks

- [x] Build UI for toggling reference layers (perhaps this could be layer-selector)
- [x] Add [the Public Water System Facilities AGOL service](https://www.arcgis.com/home/item.html?id=6f9b547041544320b8788e3e45b9d914) as a toggle-able reference layer
- [x] Add the [SITLA Land Ownership](https://opendata.gis.utah.gov/datasets/SITLA::land-ownership/about) layer
- [x] Add legend controls
