### ISSUE TITLE
Incident Flow Path

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-spills#129]
>When a spill location is created or updated, the map widget will generate a flowpath from the point that flows downgradient of the point.
Set a default small area for most spills, but provide the option to specify a larger path if necessary e.g., greater than 1/2 mile, default. Option to increase up to 15 miles.
1st priority is to get this to show up in the Salesforce widget, but it would be nice for it to show up in the incident report email as well.

Will Delaney, from Esri, suggested using the [Trace Downstream](https://pro.arcgis.com/en/pro-app/latest/tool-reference/ready-to-use/trace-downstream.htm) service in AGOL. [It appears](https://doc.arcgis.com/en/arcgis-online/analyze/credits-analysis-mv.htm#ESRI_SECTION1_F1418741E3624FE68A29D7D0D7120A4F:~:text=The%20following%20tools%20do%20not%20consume%20credits%20when%20run%20in%20ArcGIS%20Online%3A) that this service would not consume credits. This may be overkill as it traces all of the way to the ocean. I also wonder if the resolution is good enough (10 meters is the best possible, not guaranteed, resolution).

There may be other options. Risk suggested the [Global Mapper SDK](https://www.bluemarblegeo.com/global-mapper-sdk/) but it seems to be windows-only and not friendly to the web.

It would probably be best to store the results of this operation in Salesforce so that it doesn't have to be calculated every time the spill is viewed.

### Tasks

- [ ] Research and decide what solution to use
- [ ] Wire up to trigger for when the spill location is created or updated similar to #127 
- [ ] Create UI to allow the user to select a path length. 1/2 mile should be the default (and min?) with an option to increase up to 15 miles.
- [ ] Determine were to store the path in Salesforce
- [ ] Write the data to Salesforce

**Comment by stdavis** [comment]
Confirmed via our org credit usage report that trace downstream does not incur any costs.

**Comment by stdavis** [comment]
Submitted [RITM0476755](https://services.dts.utah.gov/esc?id=ticket&table=sc_req_item&sys_id=da8047eecf040bd04d1df6152f851cff&view=sp) today.

**Comment by stdavis** [comment]
Sarah said that they were ready to move this to production in an email on 5/5/26.
