### ISSUE TITLE
Define Location via Coordinates

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-spills#131]
>Change the default coordinate system to "Decimal, degrees" instead of UTM.
Ensure that all fields in the widget are automatically populated when a user clicks a location on the map.

>Reduce the number of digits displayed for decimal degree coordinates to six after the decimal point (from 14)

As a user, I should be able to define the spill location by inputting coordinates in a variety of different coordinate types. These should be validated and should directly update the map and underlying Salesforce fields automatically.

Current implementation:
![Image](https://github.com/user-attachments/assets/8f8af107-e99b-4e38-a12e-0a831f0ffcce)
![Image](https://github.com/user-attachments/assets/bb6750bb-0d09-4eeb-941c-514b6975d140)

Supported Coordinate Systems:

- Decimal Degrees (should be set as default)
- Degrees, Minutes
- Degrees, Minutes, Seconds
- UTM

They no longer want to support TRS.

It’s confusing to the user that coordinates show up in both the map widget and the SF form.
![Image](https://github.com/user-attachments/assets/f2c7b359-1d84-4d8a-a088-cb2ae098017b)

I think that we need to keep the inputs in the map widget to support entering non-default coordinate types. However, maybe they can be hidden after typing them in and hitting a submit button. They should definitely be hidden or updated when the location is updated via map click.

> [!NOTE]
> This is also [a feature](https://github.com/agrc/plss/issues/194) that needs to be built for PLSS.

### Tasks

- [x] Build UI for selecting a coordinate type and inputting coordinate values
- [x] Update pin on map and zoom
- [x] Update coordinate fields in Salesforce (converting values, if needed)
- [x] Make sure that if the location is changed by clicking on the map that the coordinates in this UI are updated as well to eliminate confusion. Or create a better UI that does not create the same kind of confusion that the current one does.
- [x] Reduce number of digits after the decimal point from 14 down to six for the values that are stored in the database.
