### ISSUE TITLE
Lead Agency Read-only Form

### ISSUE THREAD

**Issue by stdavis** [agrc/deq-spills#133]
We need to make sure that the read-only view of the Salesforce widget works and looks as expected. This is on the "Lead Agency" form. We need to ask for access to be able to test this.

![Image](https://github.com/user-attachments/assets/977b98a0-3099-4bcf-9c97-10033118663e)

This could be a use-case for the [public map](#132)

### Tasks

- [ ] Ask for access to the Lead Agency form to test in the sandbox.
- [x] Figure out a SF hook that allows us to know when the widget is in read-only mode
- [x] Switch the UI to be read only

**Comment by stdavis** [comment]
> Figure out a SF hook that allows us to know when the widget is in read-only mode

Barry suggested that we create a boolean input parameter for setting the widget as read-only.

Some example code that he sent us:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<LightningComponentBundle xmlns="http://soap.sforce.com/2006/04/metadata">
    <apiVersion>59.0</apiVersion>
    <isExposed>true</isExposed>
    <targets>
        <target>lightning__RecordPage</target>
        <target>lightningCommunity__Page</target>
        <target>lightningCommunity__Default</target>
    </targets>
    <targetConfigs>
        <targetConfig targets="lightningCommunity__Default">
      <property name="recordId" type="String" label="Record">
    <targetConfigs>
      <targetConfig targets="lightningCommunity__Default">
    <property name="recordId" type="String" label="Record ID" description="Should be set to {!recordId}"/>
</targetConfig>
    </targetConfigs>
</LightningComponentBundle>
```

> Ask for access to the Lead Agency form to test in the sandbox.

Log in as user: "Nathan Hall"
https://utahdeqorg--eid.sandbox.my.site.com/DEQ1/s/case/5003R0000050hy1QAA/detail

![Image](https://github.com/user-attachments/assets/63282390-5fba-45d7-bcdd-92b7d72898c1)

Use the “DEQ EID Portal Authorized Users”

**Comment by stdavis** [comment]
I checked today and this form is still pointed at the old widget in the sandbox. We'll need to wait for testing until a Salesforce person can help get it updated. I send an email to Sarah about it.

**Comment by stdavis** [comment]
Re-opening because this still needs acceptance testing.

**Comment by stdavis** [comment]
This has been in production for a while now so I think that we can close it.
